# Imports

In [11]:
import numpy as np

# Convert Text Data to Numerals

In [12]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [13]:
len(docs)

10

## Tokenize the dictionary
Remove special symbols <br>
Change capital letters to small letters, etc <br>


In [14]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
len(tokenizer.word_index)

17

## Text to Sequences

In [15]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

## Apply padding

In [16]:
from keras.utils import pad_sequences
vocab_size = len(tokenizer.word_index) + 1
sequences = pad_sequences(sequences, padding='post')

# Embeddings

In [17]:
from keras import Sequential
from keras.layers import *

In [18]:
model = Sequential()
model.add(Embedding(vocab_size, output_dim=2, input_length=5))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.compile('adam','accuracy')

In [20]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
[[[-0.0472681   0.03673755]
  [-0.03993988  0.01557994]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]]

 [[-0.03993988  0.01557994]
  [-0.03993988  0.01557994]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]]

 [[ 0.04879815 -0.00577144]
  [ 0.04879815 -0.00577144]
  [ 0.03323691  0.04317189]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]]

 [[-0.00066637 -0.04696474]
  [-0.00798142  0.02468245]
  [-0.00066637 -0.04696474]
  [-0.03993988  0.01557994]
  [-0.00066637 -0.04696474]]

 [[ 0.01007192 -0.00108466]
  [-0.00165777 -0.01862978]
  [ 0.03111178  0.04760757]
  [-0.00100547 -0.01709561]
  [ 0.0155237  -0.0118042 ]]

 [[ 0.01191145  0.01327045]
  [ 0.01191145  0.01327045]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042 ]]

 [[ 0.01574999  0.00351034]
  [ 0.01574999  0.00351034]
  [ 0.0155237  -0.0118042 ]
  [ 0.0155237  -0.0118042